pyproject: remove the version check
This change removes the version check since it brings just extra work for us.
Downstream uses a different naming convention that is not compatible
with upstream:

```
ERROR: Could not find a version that satisfies the requirement django-ansible-base[jwt-consumer,resource-registry]>=2025.8.18 (from ansible-ai-connect) (from versions: 2.7.0)
```