test_health_check_http_error: ensure we use the write backend
The test is designed work only if `ANSIBLE_AI_MODEL_MESH_API_TYPE` is `http` or `grpc`.
Which is fine since this is also the default value for the key.

But since people may also initialize their environment with a different environment
variables, it's better to clarify the requirement with an `override_settings()`.